defmodule DiabetesV2.Repo.Migrations.AddNewProductFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      modify :description, :text, null: true
      add :v_b9_folate_mcg, :float
      add :v_b1_thiamin_mg, :float
      add :v_b2_riboflavin_mg, :float
      add :v_b3_niacin_mg, :float
      add :v_b5_mg, :float
      add :v_b6_mg, :float
      add :v_b12_mg, :float
      add :v_c_ascorbic_acid_mg, :float
      add :v_d_mcg, :float
      add :v_k_mcg, :float
      add :v_e_mg, :float
    end
  end

  def down do
    alter table(:products) do
      remove :v_e_mg
      remove :v_k_mcg
      remove :v_d_mcg
      remove :v_c_ascorbic_acid_mg
      remove :v_b12_mg
      remove :v_b6_mg
      remove :v_b5_mg
      remove :v_b3_niacin_mg
      remove :v_b2_riboflavin_mg
      remove :v_b1_thiamin_mg
      remove :v_b9_folate_mcg
      modify :description, :text, null: false
    end
  end
end
